language: ruby
cache: bundler
rvm:
- 2.1.2
bundler_args: --jobs=8 --without development
before_install:
- wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.2.deb && sudo dpkg -i --force-confnew elasticsearch-1.3.2.deb
- wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2
- tar -xf phantomjs-1.9.7-linux-x86_64.tar.bz2
- sudo rm -rf /usr/local/phantomjs
- sudo mv phantomjs-1.9.7-linux-x86_64 /usr/local/phantomjs
services:
- elasticsearch
- redis-server
before_script:
- bundle exec rake db:setup
- bundle exec rake db:test:prepare
script:
- bundle exec rspec spec/ plugins/
- bundle exec guard-jasmine
notifications:
  slack:
    secure: DCdc+fWXLZ8ISmp4lA5NcpvJugQ/cPxLAdRxxYhvO4P3wpjpL4OXoiZHyb1lxcq9ripMrf/jqgb4p3GlYwN/1o+B9v9MwjmyyT3BQGvxVWA30XRaiCxGojfWTq2banOv6pZ3VQ7qwHVsU+8QMxlclEQUWO7yCJEoMlgIp3fWHks=
