development:
  adapter: mysql2
  encoding: utf8
  database: resource_map_development
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  database: resource_map_test
  pool: 5
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: resource_map
  pool: 5
  username: root
  password: 
